services:
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - app-network

  node-app:
    build:
      context: ./marathon-registration-node
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongo-db:27017
      - NODE_ENV=development
    volumes:
      - ./marathon-registration-node:/app

  python-app:
    build:
      context: ./marathon-registration-python
    container_name: python-app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo-db:27017
    volumes:
      - ./marathon-registration-python:/app

networks:
  app-network:
    driver: bridge
